name: Windows x64

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.9.0'
        architecture: 'x64'

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: build
      run: |
        pip3 install cython
        pip3 install pyAesCrypt
        cd src
        cython Encryption.py --embed
        cython Decryption.py --embed
        cl.exe Encryption.c /I c:\hostedtoolcache\windows\python\3.9.0\x64\include /link c:\hostedtoolcache\windows\python\3.9.0\x64\libs\python39.lib
        cl.exe Decryption.c /I c:\hostedtoolcache\windows\python\3.9.0\x64\include /link c:\hostedtoolcache\windows\python\3.9.0\x64\libs\python39.lib
        cl /EHsc Main.cpp
    - name: Upload Encryption.exe
      uses: actions/upload-artifact@v2
      with:
        path: D:\a\Password-Store\Password-Store\src\Encryption.exe
    - name: Upload Decryption.exe
      uses: actions/upload-artifact@v2
      with:
        path: D:\a\Password-Store\Password-Store\src\Decryption.exe
    - name: Upload Main.exe
      uses: actions/upload-artifact@v2
      with:
        path: D:\a\Password-Store\Password-Store\src\Main.exe
    - name: Upload Python3.9.0 DLL x64
      uses: actions/upload-artifact@v2
      with:
        path: c:\hostedtoolcache\windows\python\3.9.0\x64\python39.dll
